/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPlacesSearchRouteImport } from './routes/api/places-search'
import { Route as ApiEnrichLeadRouteImport } from './routes/api/enrich-lead'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesSearchRoute = ApiPlacesSearchRouteImport.update({
  id: '/api/places-search',
  path: '/api/places-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrichLeadRoute = ApiEnrichLeadRouteImport.update({
  id: '/api/enrich-lead',
  path: '/api/enrich-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/subscription': typeof SubscriptionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enrich-lead': typeof ApiEnrichLeadRoute
  '/api/places-search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/subscription': typeof SubscriptionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enrich-lead': typeof ApiEnrichLeadRoute
  '/api/places-search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/subscription': typeof SubscriptionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/enrich-lead': typeof ApiEnrichLeadRoute
  '/api/places-search': typeof ApiPlacesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/subscription'
    | '/api/chat'
    | '/api/enrich-lead'
    | '/api/places-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/subscription'
    | '/api/chat'
    | '/api/enrich-lead'
    | '/api/places-search'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/subscription'
    | '/api/chat'
    | '/api/enrich-lead'
    | '/api/places-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SubscriptionRoute: typeof SubscriptionRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEnrichLeadRoute: typeof ApiEnrichLeadRoute
  ApiPlacesSearchRoute: typeof ApiPlacesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places-search': {
      id: '/api/places-search'
      path: '/api/places-search'
      fullPath: '/api/places-search'
      preLoaderRoute: typeof ApiPlacesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enrich-lead': {
      id: '/api/enrich-lead'
      path: '/api/enrich-lead'
      fullPath: '/api/enrich-lead'
      preLoaderRoute: typeof ApiEnrichLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SubscriptionRoute: SubscriptionRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEnrichLeadRoute: ApiEnrichLeadRoute,
  ApiPlacesSearchRoute: ApiPlacesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
